# Generated by Django 6.0.5 on 2026-07-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField(auto_created=True)),
                ('Title', models.TextField(max_length=50)),
                ('Company_name', models.TextField(max_length=50)),
                ('Location', models.TextField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Full_Time', max_length=50)),
                ('Experience', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=1000)),
                ('Posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
