# Generated by Django 6.0.5 on 2026-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_application_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Currency',
            field=models.CharField(choices=[('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP'), ('INR', '₹ INR'), ('CAD', 'C$ CAD'), ('AUD', 'A$ AUD'), ('SGD', 'S$ SGD')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='Salary',
            field=models.IntegerField(help_text='Annual salary'),
        ),
    ]
