# Generated by Django 6.0.5 on 2026-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Candidate', 'Candidate')], default='Candidate'),
        ),
    ]
